name: Bump Version

on:
  workflow_dispatch:
    inputs:
      bump_version:
        description: 'Define the version number to bump'
        required: true
        default: patch
        type: choice
        options:
        - major
        - minor
        - patch
  workflow_call:
    inputs:
      bump_version:
        description: 'Define the version number to bump'
        required: true
        type: string

permissions:
  contents: write
  packages: write

jobs:
  bump_version:
    name: Generate Bump Version
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repository
      uses: actions/checkout@v4
    
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6.10

    - name: Bundle Install
      run: bundle check || bundle install -j 20
    
    - name: Bump Version
      id: bump_version
      run: |
        rake version:${{ inputs.bump_version }}

    - name: Commit changes and create tag
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: Bump version to ${{ steps.bump_version.outputs.new_version }}
        tagging_message: 'v${{steps.bump_version.outputs.new_version}}'
        commit_user_name: Bump Version Workflow
        file_pattern: 'lib/version.rb'
        branch: main
