name: Run On Release Created

on:
  release:
    types:
      - created

permissions:
  contents: write
  packages: write

jobs:
  tests:
    secrets: inherit
    uses: ./.github/workflows/ruby-tests.yml
  documentation:
    needs: tests
    secrets: inherit
    uses: ./.github/workflows/create-doc-page.yml