name: Create a release for the gem

on:
  workflow_dispatch:
  workflow_call:
  
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.6'

    - name: Setup OTP await
      uses: step-security/wait-for-secrets@v1
      id: wait-for-secrets
      with:
        secrets: |
          OTP: 
            name: 'OTP to publish package'
            description: 'OTP from authenticator app'
    
    - name: Install dependencies
      run: bundle check || bundle install -j 20

    - name: Build gem
      run: gem build mp-utils.gemspec

    - name: Publish gem
      env:
        GEM_HOST_API_KEY: ${{ secrets.GEM_HOST_API_KEY }}
      run: gem push mp-utils-*.gem --otp ${{ steps.wait-for-secrets.outputs.OTP }}
