name: Release Gem

on:
  release:
    types:
      - created

permissions:
  contents: read
  packages: write

jobs:
  tests:
    uses: ./.github/workflows/ruby-tests.yml
  documentation:
    needs: tests
    uses: ./.github/workflows/create-doc-page.yml
