name: Release Gem

on:
  push:
    tags:
      - 'v*.*.*'        
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  tests:
    uses: ./.github/workflows/ruby-tests.yml
  publish:
    needs: tests
    uses: ./.github/workflows/publish-gem.yml
  documentation:
    needs: publish
    uses: ./.github/workflows/create-doc-page.yml
