name: Ruby Tests

on:
  workflow_call:
  workflow_dispatch:
  
permissions:
  contents: read
  packages: write
  
jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['2.6', '2.7', '3.0', '3.2']

    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true
        
    - name: Bundle Install
      run: bundle check || bundle install -j 20
  
    - name: Rubocop
      run: bundle exec rubocop

    - name: RSpec
      run: bundle exec rspec --format documentation